<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 01: Evaluate the FAA Dataset

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: VIew and import the dataset

In [19]:
#Import necessary libraries
import pandas as pd

In [77]:
#Import the FAA (Federal Aviation Authority) dataset
df_faa_dataset = pd.read_csv('faa_ai_prelim.csv')

#### 2: View and understand the dataset

In [78]:
#View the dataset shape
df_faa_dataset.shape

(83, 42)

In [79]:
#View the first five observations
df_faa_dataset.head(5)

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
#View all the columns present in the dataset
df_faa_dataset.columns

Index([u'UPDATED', u'ENTRY_DATE', u'EVENT_LCL_DATE', u'EVENT_LCL_TIME',
       u'LOC_CITY_NAME', u'LOC_STATE_NAME', u'LOC_CNTRY_NAME', u'RMK_TEXT',
       u'EVENT_TYPE_DESC', u'FSDO_DESC', u'REGIST_NBR', u'FLT_NBR',
       u'ACFT_OPRTR', u'ACFT_MAKE_NAME', u'ACFT_MODEL_NAME',
       u'ACFT_MISSING_FLAG', u'ACFT_DMG_DESC', u'FLT_ACTIVITY', u'FLT_PHASE',
       u'FAR_PART', u'MAX_INJ_LVL', u'FATAL_FLAG', u'FLT_CRW_INJ_NONE',
       u'FLT_CRW_INJ_MINOR', u'FLT_CRW_INJ_SERIOUS', u'FLT_CRW_INJ_FATAL',
       u'FLT_CRW_INJ_UNK', u'CBN_CRW_INJ_NONE', u'CBN_CRW_INJ_MINOR',
       u'CBN_CRW_INJ_SERIOUS', u'CBN_CRW_INJ_FATAL', u'CBN_CRW_INJ_UNK',
       u'PAX_INJ_NONE', u'PAX_INJ_MINOR', u'PAX_INJ_SERIOUS', u'PAX_INJ_FATAL',
       u'PAX_INJ_UNK', u'GRND_INJ_NONE', u'GRND_INJ_MINOR',
       u'GRND_INJ_SERIOUS', u'GRND_INJ_FATAL', u'GRND_INJ_UNK'],
      dtype='object')

#### 3: Extract the following attributes from the dataset:
1. Aircraft make name
2. State name
3. Aircraft model name
4. Text information
5. Flight phase
6. Event description type
7. Fatal flag

In [81]:
#Create a new dataframe with only the required columns
df_anlayze_dataset = df_faa_dataset[['ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT','FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG']]

In [82]:
#View the type of the object
type(df_anlayze_dataset)

pandas.core.frame.DataFrame

In [83]:
#Check if the dataframe contains all the required attributes
df_anlayze_dataset.head(5)

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN

#### 4. Clean the dataset and replace the fatal flag NaN with “No”

In [84]:
#Replace all Fatal Flag missing values with the required output
df_analyze_dataset['FATAL_FLAG'].fillna(value='No', inplace=True)

In [85]:
#Verify if the missing values are replaced
df_analyze_dataset

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,ACFT_DMG_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Unknown,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Unknown,No
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Minor,No
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Unknown,No
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Minor,No
5,BELL,Hawaii,206,N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...,UNKNOWN (UNK),Substantial,No
6,PIPER,Florida,PA24,"AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...",LANDING (LDG),Unknown,No
7,CESSNA,Florida,210,"AIRCRAFT ON LANDING GEAR COLLAPSED, WINTER HAV...",LANDING (LDG),Unknown,No
8,BOEING,Florida,747,N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...,TAKEOFF (TOF),Minor,No
9,NaN,Florida,NaN,"AIRCRAFT, LSA PARADISE P1, ON LANDING NOSE GE...",LANDING (LDG),Minor,No
10,CESSNA,Virginia,172,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Unknown,No
11,NaN,Arizona,FIREFLY,"N2194X FIREFLY 9 BALLOON, ON LANDING STRUCK TH...",LANDING (LDG),None,No
12,CESSNA,New York,310,"AIRCRAFT GEAR COLLAPSED ON LANDING, ELMIRA, NY",LANDING (LDG),Unknown,No
13,CESSNA,Louisiana,210,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, LAKEF...",LANDING (LDG),Minor,No
14,BEECH,California,T34,AIRCRAFT ON TAKEOFF STRUCK RUNWAY LIGHT AT THE...,TAKEOFF (TOF),None,No
15,CESSNA,Florida,152,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR PEMBR...",LANDING (LDG),Unknown,No
16,CHRISTEN,Louisiana,EAGLE II,AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...,TAKEOFF (TOF),Substantial,No
17,PIPER,Missouri,PA34,"AIRCRAFT ON LANDING GEAR COLLAPSED, SPRINGFIEL...",LANDING (LDG),Unknown,No
18,PIPER,Florida,PA28,"AIRCRAFT ON DEPARTURE STRUCK A BIRD, RETURNED ...",TAKEOFF (TOF),Minor,No
19,CESSNA,Texas,150,"AIRCRAFT ON LANDING WENT OFF THE RUNWAY, THROU...",LANDING (LDG),Unknown,No
20,HUGHES,West Virginia,369,N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...,LANDING (LDG),Unknown,No
21,CESSNA,Texas,210,AIRCRAFT FORCE LANDED IN A FIELD 2 MILES FROM ...,UNKNOWN (UNK),Substantial,No
22,NaN,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",TAKEOFF (TOF),Substantial,Yes
23,BOEING,Michigan,737,AMERICAN AIRLINES FLIGHT AAL1241 BOEING 737 AI...,TAXI (TXI),Unknown,No
24,GLOBE,Colorado,GC1B,"AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...",LANDING (LDG),Unknown,No
25,PIPER,Tennessee,PA20,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR DAYTO...",LANDING (LDG),Unknown,No
26,GREAT LAKES,California,2T1A,"AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...",LANDING (LDG),Minor,No
27,CESSNA,New Hampshire,560,N70TH DELTA PRIVATE JET FLIGHT DPJ70 CESSNA C5...,TAXI (TXI),Unknown,No
28,CONSOLIDATED VULTEE,California,BT15,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...",TAXI (TXI),Unknown,No
29,CESSNA,Colorado,210,"AIRCRAFT LANDED GEAR UP, DURANGO, CO",LANDING (LDG),Minor,No
...,...,...,...,...,...,...,...
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Destroyed,Yes
54,CESSNA,South Dakota,150,"AIRCRAFT ON TAXI, PROP STRUCK THE GROUND, STUR...",TAXI (TXI),Substantial,No
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Destroyed,Yes
56,PIPER,Florida,PA34,"HK4699G COLUMBIA REGISTRATION, PIPER PA34 AIRC...",LANDING (LDG),None,No
57,NaN,Idaho,KITFOX,"AIRCRAFT ON LANDING GEAR COLLAPSED, HELLS CANY...",LANDING (LDG),Unknown,No
58,NaN,California,NaN,"AIRCRAFT, LIGHT SPORT DOVA AS SKYLARK, ON LAN...",LANDING (LDG),Minor,No
59,PIPER,Arizona,PA28,AIRCRAFT LANDED AND WENT OFF THE END OF THE RU...,LANDING (LDG),None,No
60,PIPER,Pennsylvania,PA34,"AIRCRAFT ON APPROACH TO LAND, STRUCK TREES, LA...",APPROACH (APR),Substantial,No
61,BEECH,California,36,AIRCRAFT FORCE LANDED IN THE WETLAND/SLOUGH AR...,LANDING (LDG),Substantial,No
62,BEECH,Arizona,33,"AIRCRAFT ON TAKEOFF, STRUCK A BIRD, RETURNED A...",TAKEOFF (TOF),Minor,No
63,CESSNA,Oregon,206,"AIRCRAFT ON LANDING, GEAR COLLAPSED, EUGENE, OR",LANDING (LDG),Minor,No
64,CESSNA,Montana,206,"AIRCRAFT ON LANDING, GEAR COLLAPSED AND STRUCK...",LANDING (LDG),Substantial,No
65,CESSNA,Oregon,175,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Substantial,No
66,PIPER,Rhode Island,PA31,"AIRCRAFT ON LANDING STRUCK A BIRD, MIDDLETOWN, RI",LANDING (LDG),Unknown,No
67,LANCAIR,Kansas,IV,"AIRCRAFT DURING FLIGHT, WINDOW SEPARATED FROM ...",UNKNOWN (UNK),Unknown,No
68,BEECH,Florida,35,"AIRCRAFT ON LANDING, NOSE GEAR COLLASPED, CRYS...",LANDING (LDG),Unknown,No
69,MOONEY,Ohio,M20K,"AIRCRAFT ON LANDING, GEAR COLLAPSED, DEFIANCE, OH",LANDING (LDG),Minor,No
70,AERO COMMANDER,Virginia,500,"AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE, VA",TAXI (TXI),Unknown,No
71,CESSNA,Georgia,310,"AIRCRAFT ON LANDING, GEAR COLLAPSED, GRIFFIN, GA",LANDING (LDG),Minor,No
72,MOONEY,Maryland,M20E,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Unknown,No
73,BEECH,California,35,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, MONT...",LANDING (LDG),None,No
74,SABRELINER,Arkansas,NA265,"AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...",LANDING (LDG),Unknown,No
75,MOONEY,Maryland,M20K,"AIRCRAFT ON LANDING, STRUCK A SIGN AND RUNWAY ...",LANDING (LDG),Minor,No
76,PIPER,Kansas,PA24,"AIRCRAFT LANDED GEAR UP, EUREKA, KS",LANDING (LDG),Minor,No
77,BOEING,Texas,737,SOUTHWEST AIRLINES FLIGHT SWA3817 BOEING 737 A...,NaN,NaN,No
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Substantial,No
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Destroyed,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Destroyed,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Destroyed,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Unknown,Yes

In [86]:
#Check the number of observations
df_analyze_dataset.shape

(83, 7)

#### 5. Remove all the observations where aircraft names are not available

In [87]:
#Drop the unwanted values/observations from the dataset
df_final_dataset = df_analyze_dataset.dropna(subset=['ACFT_MAKE_NAME'])

#### 6. Find the aircraft types and their occurrences in the dataset

In [88]:
#Check the number of observations now to compare it with the original dataset and see how many values have been dropped
df_analyze_dataset.shape

(83, 7)

In [89]:
#Group the dataset by aircraft name
aircraftType = df_final_dataset.groupby('ACFT_MAKE_NAME')

In [90]:
#View the number of times each aircraft type appears in the dataset (Hint: use the size() method)
aircraftType.size()

ACFT_MAKE_NAME
AERO COMMANDER             1
AERONCA                    1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
BEECH                      9
BELL                       2
BOEING                     3
CESSNA                    23
CHAMPION                   2
CHRISTEN                   1
CONSOLIDATED VULTEE        1
EMBRAER                    1
ENSTROM                    1
FAIRCHILD                  1
FLIGHT DESIGN              1
GLOBE                      1
GREAT LAKES                1
GRUMMAN                    1
GULFSTREAM                 1
HUGHES                     1
LANCAIR                    2
MAULE                      1
MOONEY                     4
NORTH AMERICAN             1
PIPER                     10
PITTS                      1
SAAB                       1
SABRELINER                 1
SOCATA                     2
VANS                       1
dtype: int64

#### 7: Display the observations where fatal flag is “Yes”

In [91]:
#Group the dataset by fatal flag
fatalAccidents = df_final_dataset.groupby('FATAL_FLAG')

In [92]:
#View the total number of fatal and non-fatal accidents
fatalAccidents.size()

FATAL_FLAG
No     71
Yes     7
dtype: int64

In [93]:
#Create a new dataframe to view only the fatal accidents (Fatal Flag values = Yes)
fatalAccidents.get_group('Yes')

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,ACFT_DMG_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Unknown,Yes
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Destroyed,Yes
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Destroyed,Yes
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Destroyed,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Destroyed,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Destroyed,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Unknown,Yes